[package]
name = "mqtt_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.19"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
